# Generated by Django 5.1.4 on 2025-01-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea_pedidos',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='linea_pedidos',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
